export const X_REFERENCE_COVERAGE = {
  surfaces: [
    "app-shell-navigation",
    "home-for-you",
    "home-following",
    "search-results",
    "explore-trends",
    "notifications",
    "history-bookmarks",
    "lists-directory",
    "list-timeline",
    "user-profile",
    "post-detail",
    "conversation-replies",
    "media-detail",
    "composer-post",
    "composer-reply",
    "composer-quote",
    "direct-messages-inbox",
    "direct-message-thread",
    "account-switcher",
    "login-session",
    "settings",
    "communities",
    "community-posts",
    "spaces-audio",
    "live-events",
    "articles-reader",
    "grok-chat",
    "premium-creator-business",
    "ads-promoted-content",
    "errors-interstitials",
    "dialogs-popovers-menus-toasts",
  ],
  contentKinds: [
    "text-post",
    "long-post",
    "reply",
    "repost",
    "quote-post",
    "image-single",
    "image-gallery",
    "animated-gif",
    "video",
    "live-video",
    "link-card",
    "x-article",
    "poll",
    "space",
    "community-note",
    "trend",
    "notification",
    "direct-message",
    "list",
    "user",
    "promoted-content",
    "tombstone",
    "unavailable-content",
  ],
  elementKinds: [
    "navigation-item",
    "tab",
    "post-card",
    "author-identity",
    "social-context",
    "post-text-entity",
    "hashtag",
    "cashtag",
    "mention",
    "external-link",
    "quote-card",
    "community-note-card",
    "media-grid",
    "image-viewer",
    "video-player",
    "audio-player",
    "reply-tree",
    "engagement-bar",
    "overflow-menu",
    "tooltip",
    "popover",
    "dialog",
    "toast",
    "banner",
    "form-control",
    "virtualized-list",
    "pagination-cursor",
    "skeleton",
    "empty-state",
    "error-state",
  ],
  states: [
    "initial",
    "loading",
    "ready",
    "empty",
    "refreshing",
    "paginating",
    "new-content-pending",
    "optimistic-pending",
    "success",
    "error",
    "retrying",
    "rate-limited",
    "offline",
    "disabled",
    "focused",
    "hovered",
    "pressed",
    "expanded",
    "collapsed",
    "selected",
    "translated",
    "showing-original",
    "sensitive-hidden",
    "sensitive-revealed",
    "deleted",
    "private",
    "blocked",
    "muted",
    "unavailable",
    "live",
    "ended",
  ],
  inputs: [
    "pointer-click",
    "pointer-double-click",
    "pointer-hover",
    "pointer-drag",
    "wheel-scroll",
    "keyboard-tab",
    "keyboard-enter",
    "keyboard-space",
    "keyboard-escape",
    "keyboard-arrows",
    "keyboard-shortcut",
    "touch-tap",
    "touch-double-tap",
    "touch-long-press",
    "touch-pan",
    "touch-pinch",
    "touch-pull-refresh",
    "system-back",
    "history-forward-back",
  ],
  environments: [
    "desktop-wide",
    "desktop-narrow",
    "tablet-landscape",
    "tablet-portrait",
    "phone-portrait",
    "phone-landscape",
    "low-height",
    "high-dpi",
    "ltr",
    "rtl",
    "light",
    "dark",
    "reduced-motion",
    "keyboard-only",
    "touch-only",
  ],
  dataConditions: [
    "single-account",
    "multiple-accounts",
    "logged-out",
    "logged-in",
    "public-content",
    "protected-content",
    "self-authored",
    "other-authored",
    "verified-author",
    "unverified-author",
    "zero-engagement",
    "large-engagement",
    "short-text",
    "long-text",
    "mixed-script",
    "emoji",
    "rtl-content",
    "missing-optional-fields",
    "malformed-response",
    "duplicate-entries",
    "out-of-order-events",
    "slow-network",
    "request-failure",
  ],
} as const;

export const NYTD_PRODUCT_INVARIANTS = [
  {
    id: "freely-addable-unbounded-columns",
    rule: "利用者が任意種類のカラムを任意数追加・削除・並べ替えでき、再起動後も復元する",
  },
  {
    id: "persistent-left-main-menu",
    rule: "TweetDeck型の左メインメニューを維持し、単一フィード型ナビゲーションへ置き換えない",
  },
  {
    id: "customizable-main-menu",
    rule: "左メインメニューの項目を追加・削除・並べ替えでき、その配置を永続化する",
  },
  {
    id: "persistent-multiple-accounts",
    rule: "複数アカウントのログイン状態を保持し、自動選択・切替・アカウント別データ分離を維持する",
  },
] as const;

export type CoverageDimension = keyof typeof X_REFERENCE_COVERAGE;

export function coverageCatalogCounts(): Record<CoverageDimension, number> {
  return Object.fromEntries(
    Object.entries(X_REFERENCE_COVERAGE).map(([dimension, values]) => [dimension, values.length]),
  ) as Record<CoverageDimension, number>;
}
