server:
  address: 127.0.0.1
  port: 8080
  error:
    include-message: never
    include-stacktrace: never

spring:
  application:
    name: nytweetdeck
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
