server:
  address: 127.0.0.1
  port: 18080
  error:
    include-message: never
    include-stacktrace: never

spring:
  application:
    name: nytweetdeck
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 16MB
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
