package dev.nytweetdeck.android.ui

import android.app.DatePickerDialog
import android.app.TimePickerDialog
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.imePadding
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.safeDrawingPadding
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Button
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.FilterChip
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalSoftwareKeyboardController
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.unit.dp
import coil3.compose.AsyncImage
import dev.nytweetdeck.android.R
import dev.nytweetdeck.android.model.ComposerMode
import dev.nytweetdeck.android.model.ComposerPlace
import dev.nytweetdeck.android.model.ComposerPoll
import dev.nytweetdeck.android.model.ComposerStatus
import dev.nytweetdeck.android.model.ComposerSubmission
import dev.nytweetdeck.android.model.ComposerUiState
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import kotlinx.coroutines.launch

private const val MAX_COMPOSER_CHARACTERS = 4_000

@Composable
internal fun AdvancedComposerDialog(
    state: ComposerUiState,
    onSubmit: (ComposerSubmission) -> Unit,
    onSearchPlaces: suspend (String) -> List<ComposerPlace>,
    onDismiss: () -> Unit,
) {
    val context = LocalContext.current
    val mediaLimitMessage = stringResource(R.string.composer_media_limit)
    val placeSearchError = stringResource(R.string.composer_place_error)
    val keyboardController = LocalSoftwareKeyboardController.current
    val scope = rememberCoroutineScope()
    var text by rememberSaveable(state.mode, state.targetPostId) { mutableStateOf("") }
    var mediaUris by remember(state.mode, state.targetPostId) { mutableStateOf<List<Uri>>(emptyList()) }
    var gifSelected by remember(state.mode, state.targetPostId) { mutableStateOf(false) }
    var pollChoices by remember(state.mode, state.targetPostId) { mutableStateOf<List<String>?>(null) }
    var pollDuration by rememberSaveable(state.mode, state.targetPostId) { mutableIntStateOf(1440) }
    var showEmoji by remember { mutableStateOf(false) }
    var scheduledAt by remember { mutableStateOf<Instant?>(null) }
    var showPlaceSearch by remember { mutableStateOf(false) }
    var placeQuery by rememberSaveable { mutableStateOf("") }
    var placeOptions by remember { mutableStateOf<List<ComposerPlace>>(emptyList()) }
    var selectedPlace by remember { mutableStateOf<ComposerPlace?>(null) }
    var searchingPlaces by remember { mutableStateOf(false) }
    var showDisclosure by remember { mutableStateOf(false) }
    var paidPartnership by remember { mutableStateOf(false) }
    var aiGenerated by remember { mutableStateOf(false) }
    var localError by remember { mutableStateOf<String?>(null) }
    val isSending = state.status == ComposerStatus.SENDING
    val canEdit = !isSending && state.status != ComposerStatus.SUCCEEDED
    val isTargeted = state.mode != ComposerMode.POST
    val hasTarget = !isTargeted || !state.targetPostId.isNullOrBlank()
    val count = text.codePointCount(0, text.length)
    val pollValid = pollChoices?.let { it.size in 2..4 && it.all(String::isNotBlank) } ?: true
    val canSubmit = canEdit && hasTarget && count <= MAX_COMPOSER_CHARACTERS && pollValid &&
        (text.isNotBlank() || mediaUris.isNotEmpty() || pollChoices != null)

    val imagePicker = rememberLauncherForActivityResult(ActivityResultContracts.OpenMultipleDocuments()) { selected ->
        val merged = (mediaUris + selected).distinct()
        if (gifSelected || merged.size > 4 || pollChoices != null) {
            localError = mediaLimitMessage
        } else {
            mediaUris = merged
            localError = null
        }
    }
    val gifPicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { selected ->
        if (selected != null && pollChoices == null) {
            mediaUris = listOf(selected)
            gifSelected = true
            localError = null
        }
    }

    FullScreenRouteSurface(tag = "composer-route", onDismiss = { if (!isSending) onDismiss() }) {
        Column(
            modifier = Modifier.fillMaxSize().safeDrawingPadding().imePadding()
                .verticalScroll(rememberScrollState()).padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp),
        ) {
            Row(Modifier.fillMaxWidth()) {
                Column {
                    Text(when (state.mode) {
                        ComposerMode.POST -> stringResource(R.string.composer_mode_post)
                        ComposerMode.REPLY -> stringResource(R.string.composer_mode_reply)
                        ComposerMode.QUOTE -> stringResource(R.string.composer_mode_quote)
                    })
                    state.targetPostId?.let { Text(stringResource(R.string.composer_target_post_id, it)) }
                }
                Spacer(Modifier.weight(1f))
                TextButton(onClick = onDismiss, enabled = !isSending, modifier = Modifier.testTag("close-composer")) {
                    Text(stringResource(R.string.close))
                }
            }
            OutlinedTextField(
                value = text,
                onValueChange = { updated ->
                    if (updated.codePointCount(0, updated.length) <= MAX_COMPOSER_CHARACTERS) text = updated
                },
                modifier = Modifier.fillMaxWidth().testTag("composer-text"),
                label = { Text(stringResource(R.string.post_text)) },
                enabled = canEdit,
                minLines = 5,
            )
            Text(stringResource(R.string.composer_character_count, count, MAX_COMPOSER_CHARACTERS),
                style = MaterialTheme.typography.labelMedium)

            if (mediaUris.isNotEmpty()) {
                Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    mediaUris.forEach { uri ->
                        Column {
                            AsyncImage(model = uri, contentDescription = null, modifier = Modifier.size(84.dp))
                            TextButton(onClick = {
                                mediaUris = mediaUris - uri
                                if (mediaUris.isEmpty()) gifSelected = false
                            }, enabled = canEdit) { Text(stringResource(R.string.composer_remove)) }
                        }
                    }
                }
            }

            Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),
                horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                TextButton(onClick = { imagePicker.launch(arrayOf("image/png", "image/jpeg")) },
                    enabled = canEdit && !gifSelected && pollChoices == null,
                    modifier = Modifier.testTag("composer-add-image")) { Text(stringResource(R.string.composer_image)) }
                TextButton(onClick = { gifPicker.launch("image/gif") }, enabled = canEdit && pollChoices == null,
                    modifier = Modifier.testTag("composer-add-gif")) { Text(stringResource(R.string.composer_gif)) }
                TextButton(onClick = { pollChoices = if (pollChoices == null) listOf("", "") else null },
                    enabled = canEdit && !isTargeted && mediaUris.isEmpty() && scheduledAt == null,
                    modifier = Modifier.testTag("composer-toggle-poll")) { Text(stringResource(R.string.composer_poll)) }
                TextButton(onClick = { showEmoji = !showEmoji }, enabled = canEdit,
                    modifier = Modifier.testTag("composer-toggle-emoji")) { Text(stringResource(R.string.composer_emoji)) }
                TextButton(onClick = {
                    if (scheduledAt != null) scheduledAt = null else {
                        val initial = LocalDateTime.now().plusHours(1)
                        DatePickerDialog(context, { _, year, month, day ->
                            TimePickerDialog(context, { _, hour, minute ->
                                scheduledAt = LocalDateTime.of(year, month + 1, day, hour, minute)
                                    .atZone(ZoneId.systemDefault()).toInstant()
                                showPlaceSearch = false
                                placeOptions = emptyList()
                            }, initial.hour, initial.minute, true).show()
                        }, initial.year, initial.monthValue - 1, initial.dayOfMonth).show()
                    }
                }, enabled = canEdit && !isTargeted && pollChoices == null && selectedPlace == null,
                    modifier = Modifier.testTag("composer-toggle-schedule")) { Text(stringResource(R.string.composer_schedule)) }
                TextButton(onClick = { showPlaceSearch = !showPlaceSearch },
                    enabled = canEdit && scheduledAt == null,
                    modifier = Modifier.testTag("composer-toggle-place")) { Text(stringResource(R.string.composer_place)) }
                TextButton(onClick = { showDisclosure = !showDisclosure }, enabled = canEdit,
                    modifier = Modifier.testTag("composer-toggle-disclosure")) { Text(stringResource(R.string.composer_disclosure)) }
            }

            if (showEmoji) {
                listOf("😀", "😂", "🥹", "😍", "😊", "😎", "🤔", "😭", "❤️", "✨", "🔥", "👍", "🙏", "🎉", "🌸", "💡")
                    .chunked(8).forEach { row ->
                        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            row.forEach { emoji -> TextButton(onClick = {
                                if ((text + emoji).length <= MAX_COMPOSER_CHARACTERS) text += emoji
                                showEmoji = false
                            }) { Text(emoji) } }
                        }
                    }
            }
            pollChoices?.let { choices ->
                Text(stringResource(R.string.composer_poll_choices), style = MaterialTheme.typography.titleSmall)
                choices.forEachIndexed { index, choice ->
                    OutlinedTextField(value = choice, onValueChange = { value ->
                        if (value.length <= 25) pollChoices = choices.mapIndexed { position, current ->
                            if (position == index) value else current
                        }
                    }, label = { Text(stringResource(R.string.composer_poll_choice, index + 1)) },
                        keyboardOptions = KeyboardOptions(imeAction = ImeAction.Done),
                        keyboardActions = KeyboardActions(onDone = { keyboardController?.hide() }),
                        enabled = canEdit, modifier = Modifier.fillMaxWidth().testTag("composer-choice-${index + 1}"))
                }
                if (choices.size < 4) TextButton(onClick = { pollChoices = choices + "" }, enabled = canEdit) {
                    Text(stringResource(R.string.composer_add_choice))
                }
                if (choices.size > 2) TextButton(onClick = { pollChoices = choices.dropLast(1) }, enabled = canEdit) {
                    Text(stringResource(R.string.composer_remove_choice))
                }
                Text(stringResource(R.string.composer_poll_duration))
                Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),
                    horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                    listOf(60, 360, 1440, 4320, 10080).forEach { minutes ->
                        FilterChip(selected = pollDuration == minutes, onClick = { pollDuration = minutes },
                            label = { Text(pollDurationLabel(minutes)) },
                            modifier = Modifier.testTag("composer-duration-$minutes"))
                    }
                }
            }
            scheduledAt?.let { at ->
                Text(stringResource(R.string.composer_scheduled_for,
                    DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm").withZone(ZoneId.systemDefault()).format(at)))
            }
            if (showPlaceSearch) {
                OutlinedTextField(value = placeQuery, onValueChange = { placeQuery = it.take(100) },
                    label = { Text(stringResource(R.string.composer_place_search)) },
                    modifier = Modifier.fillMaxWidth().testTag("composer-place-query"))
                TextButton(onClick = {
                    searchingPlaces = true
                    scope.launch {
                        runCatching { onSearchPlaces(placeQuery) }
                            .onSuccess { placeOptions = it }
                            .onFailure { localError = placeSearchError }
                        searchingPlaces = false
                    }
                }, enabled = canEdit && !searchingPlaces && placeQuery.isNotBlank(),
                    modifier = Modifier.testTag("composer-place-search")) {
                    Text(stringResource(R.string.search))
                }
                selectedPlace?.let { place ->
                    TextButton(onClick = { selectedPlace = null }) { Text("${place.name} ×") }
                }
                placeOptions.take(10).forEach { option ->
                    TextButton(onClick = { selectedPlace = option; placeOptions = emptyList() },
                        enabled = canEdit, modifier = Modifier.fillMaxWidth()
                            .testTag("composer-place-option-${option.id}")) { Text(option.name) }
                }
            }
            if (showDisclosure) {
                Text(stringResource(R.string.composer_disclosure), style = MaterialTheme.typography.titleSmall)
                Row(Modifier.fillMaxWidth()) {
                    Checkbox(checked = paidPartnership, onCheckedChange = { paidPartnership = it },
                        enabled = canEdit, modifier = Modifier.testTag("composer-paid-partnership"))
                    Text(stringResource(R.string.composer_paid_partnership))
                }
                Row(Modifier.fillMaxWidth()) {
                    Checkbox(checked = aiGenerated, onCheckedChange = { aiGenerated = it },
                        enabled = canEdit, modifier = Modifier.testTag("composer-ai-generated"))
                    Text(stringResource(R.string.composer_ai_generated))
                }
            }
            localError?.let { Text(it, color = MaterialTheme.colorScheme.error) }
            if (!hasTarget) Text(stringResource(R.string.composer_target_missing), color = MaterialTheme.colorScheme.error)
            state.errorMessage?.let { Text(it, color = MaterialTheme.colorScheme.error) }
            if (state.status == ComposerStatus.FAILED) Text(stringResource(R.string.composer_status_failed),
                color = MaterialTheme.colorScheme.error)
            Button(onClick = {
                onSubmit(ComposerSubmission(
                    text = text,
                    mediaUris = mediaUris,
                    poll = pollChoices?.let { ComposerPoll(it, pollDuration) },
                    scheduledAt = scheduledAt,
                    place = selectedPlace,
                    paidPartnership = paidPartnership,
                    aiGenerated = aiGenerated,
                ))
            }, enabled = canSubmit, modifier = Modifier.fillMaxWidth().testTag("send-composer")) {
                if (isSending) CircularProgressIndicator(Modifier.size(18.dp), strokeWidth = 2.dp)
                Text(when {
                    isSending -> stringResource(R.string.composer_status_sending)
                    scheduledAt != null -> stringResource(R.string.composer_schedule_send)
                    state.status == ComposerStatus.FAILED -> stringResource(R.string.composer_resend)
                    else -> stringResource(R.string.composer_send)
                })
            }
            Spacer(Modifier.height(12.dp))
        }
    }
}

@Composable
private fun pollDurationLabel(minutes: Int): String = when (minutes) {
    60 -> stringResource(R.string.composer_duration_hour)
    360 -> stringResource(R.string.composer_duration_six_hours)
    1440 -> stringResource(R.string.composer_duration_day)
    4320 -> stringResource(R.string.composer_duration_three_days)
    else -> stringResource(R.string.composer_duration_week)
}
